/* eslint-disable */
/* Auto-generated by scripts/embedAcquisitionEmails.mjs — do not edit */

export const ACQUISITION_EMAIL_SOURCE_FILES = [
  { filename: "01_initial_acquisition_interest.txt", content: `From: Sarah McKenzie <sarah.mckenzie@harbourfoods.co.nz>
To: James Patel <james.patel@northshorelegal.co.nz>
Cc: Mark Allen <mark.allen@harbourfoods.co.nz>
Date: Monday, 6 May 2026, 8:42 AM
Subject: Confidential - potential acquisition of Southern Valley Organics

Hi James,

Hope you had a good weekend.

We are looking at a potential acquisition of Southern Valley Organics Limited, a small but fast-growing organic meal-kit and wholesale food business based in Nelson. They supply a number of supermarkets and have a direct-to-consumer subscription platform.

We are not at heads of agreement stage yet, but the founders have indicated they would be open to a sale of 100% of the shares. The price being discussed informally is around NZD $8.2m, subject to due diligence and normal adjustments.

Our commercial rationale is mainly:
- access to their South Island supplier network;
- their subscription customer base;
- their proprietary meal planning software; and
- the brand, which has a strong reputation with younger urban customers.

We would like your help preparing a legal issues memo for the board before we go any further. At this stage the board wants to know what the main legal risks are, what due diligence we should request, and whether there are any obvious deal blockers.

Timing is tight. Mark is meeting their CEO on Thursday and would like to be able to say we have legal workstreams underway. Could you please treat this as confidential and not contact Southern Valley directly until we have an NDA in place.

Thanks,

Sarah

Sarah McKenzie
General Counsel
Harbour Foods Group Limited
sarah.mckenzie@harbourfoods.co.nz
+64 21 555 018
` },
  { filename: "02_forwarded_target_summary.txt", content: `From: Mark Allen <mark.allen@harbourfoods.co.nz>
To: Sarah McKenzie <sarah.mckenzie@harbourfoods.co.nz>
Cc: James Patel <james.patel@northshorelegal.co.nz>
Date: Monday, 6 May 2026, 10:17 AM
Subject: Fwd: Southern Valley - quick background notes

Hi Sarah,

Forwarding my rough notes from last week. James, these are not polished and some of this is just what Tom told me verbally, so please treat it as unverified.

Key points:
- Southern Valley Organics started in 2018.
- Founders are Tom Reeves and Priya Nair. Tom is CEO, Priya runs product/tech.
- Revenue FY25 was apparently around $6.4m, EBITDA approx $900k.
- Staff: 38 permanent employees and about 25 casual packing staff during peak periods.
- They lease their Nelson warehouse. Lease expires September 2027, but Tom said the landlord is "friendly" and would probably extend.
- They have a supply agreement with GreenFields Co-op. Tom says it is their most important supplier.
- They have about 18,000 active subscription customers.
- They hold a lot of customer dietary preference data and delivery instructions.
- They use a software platform called PantryPilot that Priya built before the company was incorporated. Need to check who owns that.
- They had some sort of website outage last summer and a few customers complained about double charges. Tom brushed it off.
- Their CFO left in March. Tom said it was "not a big issue" but worth checking.

The founders seem motivated but are pushing for a fast process. Tom said if we are serious, they want a non-binding offer within 10 days.

Cheers,

Mark

Mark Allen
Chief Strategy Officer
Harbour Foods Group Limited
mark.allen@harbourfoods.co.nz
` },
  { filename: "03_nda_and_process.txt", content: `From: James Patel <james.patel@northshorelegal.co.nz>
To: Sarah McKenzie <sarah.mckenzie@harbourfoods.co.nz>
Cc: Mark Allen <mark.allen@harbourfoods.co.nz>
Date: Monday, 6 May 2026, 1:03 PM
Subject: Re: Confidential - potential acquisition of Southern Valley Organics

Hi Sarah,

Thanks, understood. We will not contact the target or its advisers until you confirm an NDA is signed.

At this stage I suggest we focus the initial memo on:
1. Transaction structure: share purchase versus asset purchase.
2. Core due diligence requests: corporate, financial, commercial contracts, employment, property, IP/software, privacy/data, food regulatory, litigation/disputes, and tax.
3. Key red flags from the early facts: ownership of PantryPilot, supplier dependency, customer data/privacy, lease term, employment/casual workforce, and any customer billing issues.
4. Approval/timing issues: board process, financing, conditions precedent, and any third-party consents.
5. Public messaging/confidentiality.

Could you please send through any draft NDA, process letter, teaser, information memorandum, or financial summary you have received? If there is nothing formal yet, the internal notes are enough for us to start a first-pass legal issues memo.

Also, if the board is meeting this week, please confirm the deadline for the memo. We can prepare something board-level and practical rather than a full diligence report.

Kind regards,

James

James Patel
Partner
Northshore Legal
james.patel@northshorelegal.co.nz
+64 9 555 2211
` },
  { filename: "04_target_ceo_intro.txt", content: `From: Tom Reeves <tom.reeves@southernvalleyorganics.co.nz>
To: Mark Allen <mark.allen@harbourfoods.co.nz>
Cc: Sarah McKenzie <sarah.mckenzie@harbourfoods.co.nz>
Date: Tuesday, 7 May 2026, 7:56 AM
Subject: Southern Valley / Harbour Foods - next steps

Hi Mark,

Good speaking last week.

Priya and I are open to exploring a transaction with Harbour Foods. As discussed, we would prefer a clean share sale rather than selling particular assets, mostly because we do not want to spend months unpicking supplier contracts, employment arrangements, and the customer platform.

For context, we have had two other parties ask for information. Neither is as strategically aligned as Harbour Foods, but it does mean we cannot let this drift.

We can provide a basic data room after the NDA is signed. It will include:
- constitution and shareholder records;
- recent management accounts;
- top customer and supplier contracts;
- lease documents;
- employment agreement templates;
- software and IP documents; and
- privacy policy and terms of use.

We would like any indicative offer by Friday 17 May if possible. We are not expecting a binding SPA by then, just enough certainty on price, structure, and process.

Regards,

Tom

Tom Reeves
Co-Founder & CEO
Southern Valley Organics Limited
tom.reeves@southernvalleyorganics.co.nz
+64 27 444 709
` },
  { filename: "05_internal_concerns.txt", content: `From: Sarah McKenzie <sarah.mckenzie@harbourfoods.co.nz>
To: James Patel <james.patel@northshorelegal.co.nz>
Cc: Mark Allen <mark.allen@harbourfoods.co.nz>
Date: Tuesday, 7 May 2026, 9:24 AM
Subject: Re: Southern Valley / Harbour Foods - next steps

Hi James,

This has moved quickly. I have attached the NDA separately and we expect it to be signed today.

For the memo, please assume the board will want something by 5 PM this Friday. It does not need to be perfect, but it does need to identify the issues that could affect whether we submit an indicative offer next week.

My immediate concerns are:
- share purchase may bring all historic liabilities with it;
- software ownership sounds unclear;
- customer database could be very valuable but also a privacy risk;
- supply contract concentration;
- casual labour arrangements;
- lease expiry in 2027; and
- whether there are food safety or product recall issues.

Can you also cover whether we should insist on completion conditions around supplier consent, landlord consent, software assignment/confirmation, and no material privacy breach?

Thanks,

Sarah
` },
  { filename: "06_due_diligence_data_room.txt", content: `From: Priya Nair <priya.nair@southernvalleyorganics.co.nz>
To: Mark Allen <mark.allen@harbourfoods.co.nz>
Cc: Tom Reeves <tom.reeves@southernvalleyorganics.co.nz>; Sarah McKenzie <sarah.mckenzie@harbourfoods.co.nz>
Date: Tuesday, 7 May 2026, 4:38 PM
Subject: Data room now open

Hi Mark and Sarah,

The NDA is signed, so I have opened the data room.

A few notes so your team is not surprised:
- The PantryPilot platform started as my personal side project in 2017. I then adapted it for Southern Valley once the company started trading.
- We do not have a long-form software assignment deed. The board minutes from 2019 record that the company would use and develop the platform.
- Two contractors in India helped build the subscription dashboard in 2021. I am looking for the contractor agreements but have not found signed copies yet.
- We use Stripe for payments and Klaviyo for customer emails.
- We had a billing bug in January 2026 that affected about 370 customers. All refunds were processed within a week.
- We have not had any regulator involvement in relation to that issue.

Please send any diligence questions through me rather than directly to the team. We are trying to keep this limited internally for now.

Best,

Priya

Priya Nair
Co-Founder & Chief Product Officer
Southern Valley Organics Limited
priya.nair@southernvalleyorganics.co.nz
` },
  { filename: "07_supplier_contract_issue.txt", content: `From: Mark Allen <mark.allen@harbourfoods.co.nz>
To: Sarah McKenzie <sarah.mckenzie@harbourfoods.co.nz>; James Patel <james.patel@northshorelegal.co.nz>
Date: Wednesday, 8 May 2026, 8:11 AM
Subject: GreenFields contract - possible consent issue

Morning both,

I had a look at the GreenFields supply agreement in the data room last night. It looks like GreenFields supplies around 62% of Southern Valley's fresh produce by value.

Clause 14 says Southern Valley must not assign, novate, transfer, or undergo a "change in control" without GreenFields' prior written consent. It also says consent must not be unreasonably withheld, but GreenFields can require evidence of financial standing and operational capacity.

This seems important. If we buy the shares, there is a change in control. If we do an asset deal, we probably need assignment or novation anyway.

Tom says GreenFields will be fine with Harbour Foods as owner because we are larger and more stable. That may be true, but I would rather not rely on a handshake.

James, can you please include this in the memo as a key condition precedent / diligence item?

Cheers,

Mark
` },
  { filename: "08_employment_and_founders.txt", content: `From: Emma Liu <emma.liu@harbourfoods.co.nz>
To: Sarah McKenzie <sarah.mckenzie@harbourfoods.co.nz>
Cc: James Patel <james.patel@northshorelegal.co.nz>
Date: Wednesday, 8 May 2026, 11:46 AM
Subject: Southern Valley - employment points

Hi Sarah,

I reviewed the employment folder briefly.

Initial observations:
- There are standard individual employment agreements for permanent staff.
- Casual packing staff appear to be engaged using a short letter agreement. The letters are very basic.
- Some casuals have worked regular shifts for more than 12 months. That may create risk if they are really permanent part-time employees in practice.
- There is no obvious restraint of trade for Tom or Priya.
- The head of operations, Daniel Morris, has a six-month notice period and a change-of-control bonus equal to six months' salary.
- There is a draft employee share option plan from 2022 but I cannot tell whether any options were actually granted.

If the founders are critical to the value of the business, we probably need service agreements or consultancy arrangements as part of the transaction. Priya in particular seems essential because of the software.

Happy to help more if useful.

Thanks,

Emma

Emma Liu
People & Culture Manager
Harbour Foods Group Limited
emma.liu@harbourfoods.co.nz
` },
  { filename: "09_privacy_and_customer_data.txt", content: `From: Rachel Ngata <rachel.ngata@northshorelegal.co.nz>
To: James Patel <james.patel@northshorelegal.co.nz>
Cc: Sarah McKenzie <sarah.mckenzie@harbourfoods.co.nz>
Date: Wednesday, 8 May 2026, 2:15 PM
Subject: Privacy review - Southern Valley customer platform

Hi James,

I have completed a first-pass privacy review from the materials provided.

Key points:
- Southern Valley holds names, addresses, phone numbers, payment tokens, dietary preferences, delivery instructions, and customer service notes.
- Some delivery notes include sensitive details customers typed manually, e.g. "leave at back door, baby sleeping", "elderly parent at home", and health/allergy information.
- The privacy policy is short and has not been updated since 2021.
- It says customer information is used for "order fulfilment and marketing of related products", but it does not clearly explain data sharing in an acquisition context.
- The January 2026 billing bug does not appear to have involved unauthorised access, but the records are thin.
- I cannot see a formal privacy breach register or incident response plan.

For the board memo, I would flag that the customer database is an asset but also a diligence focus. We should request:
1. incident logs;
2. complaints/refund records from the billing bug;
3. vendor contracts with Stripe, Klaviyo, and hosting providers;
4. data retention/deletion policy;
5. any privacy impact assessments; and
6. confirmation whether customer consent or updated notices are needed before post-completion data integration.

Regards,

Rachel

Rachel Ngata
Senior Associate
Northshore Legal
rachel.ngata@northshorelegal.co.nz
` },
  { filename: "10_property_lease.txt", content: `From: James Patel <james.patel@northshorelegal.co.nz>
To: Sarah McKenzie <sarah.mckenzie@harbourfoods.co.nz>
Cc: Mark Allen <mark.allen@harbourfoods.co.nz>
Date: Thursday, 9 May 2026, 9:32 AM
Subject: Southern Valley lease issue

Hi Sarah,

We have now reviewed the Nelson warehouse lease.

A few points for the memo:
- Current term expires 30 September 2027.
- There is one right of renewal for three years, but it must be exercised by giving written notice at least six months before expiry.
- The lease contains a change of control provision requiring landlord consent where there is a material change in the ownership of the tenant.
- The lease also restricts alterations to refrigeration and packing areas without landlord consent.
- There is no obvious rent arrears issue from the documents, but outgoings reconciliation is missing for FY25.

This is not necessarily a deal blocker, but if the warehouse is operationally important, landlord consent and confirmation of renewal rights should be conditions to completion. We should also check whether any refrigeration works were done without approval.

Kind regards,

James
` },
  { filename: "11_food_safety_and_recall.txt", content: `From: Olivia Turner <olivia.turner@harbourfoods.co.nz>
To: Sarah McKenzie <sarah.mckenzie@harbourfoods.co.nz>; Mark Allen <mark.allen@harbourfoods.co.nz>
Cc: James Patel <james.patel@northshorelegal.co.nz>
Date: Thursday, 9 May 2026, 12:08 PM
Subject: Food safety diligence - initial comments

Hi team,

I reviewed the food safety documents in the data room.

There is a registered food control plan and audit reports for 2024 and 2025. The 2025 audit report notes three corrective actions:
1. temperature logs for chilled storage were incomplete on several days;
2. allergen labelling checks were not consistently signed off;
3. one supplier certificate was expired.

The report says all corrective actions were closed by 15 February 2026. I have not yet seen supporting evidence for closure, just the target's summary.

There was also a small voluntary recall in August 2024 for a mislabelled sesame allergen in a salad dressing sachet. The recall looks contained, but we should ask for:
- recall notices;
- regulator correspondence;
- customer complaints;
- insurance notifications; and
- evidence that labelling controls changed afterwards.

From a commercial perspective, I do not think this kills the deal, but it should definitely be in the due diligence request list and warranties.

Regards,

Olivia

Olivia Turner
Quality & Compliance Lead
Harbour Foods Group Limited
olivia.turner@harbourfoods.co.nz
` },
  { filename: "12_financing_and_board_deadline.txt", content: `From: David Chen <david.chen@harbourfoods.co.nz>
To: Sarah McKenzie <sarah.mckenzie@harbourfoods.co.nz>; Mark Allen <mark.allen@harbourfoods.co.nz>
Cc: James Patel <james.patel@northshorelegal.co.nz>
Date: Thursday, 9 May 2026, 3:27 PM
Subject: Board paper timing and acquisition funding

Hi Sarah and Mark,

The board pack closes tomorrow at midday. If we want the Southern Valley memo included, we need a near-final version by 10:30 AM Friday.

On funding, we can likely finance the acquisition from existing debt facilities, but the CFO wants to confirm whether the bank needs to consent to any acquisition over $5m. I am checking the facility agreement tonight.

Please make sure the legal memo covers:
- whether the offer should be expressly non-binding;
- what conditions should attach to any indicative offer;
- what approvals are needed internally;
- whether we need bank consent before signing a binding SPA;
- whether to require founder retention arrangements; and
- whether we should prefer share purchase or asset purchase given the issues emerging.

James, please keep it board-friendly. They will not want a 20-page legal essay.

Thanks,

David

David Chen
Chief Financial Officer
Harbour Foods Group Limited
david.chen@harbourfoods.co.nz
` },
  { filename: "13_draft_memo_instructions.txt", content: `From: Sarah McKenzie <sarah.mckenzie@harbourfoods.co.nz>
To: James Patel <james.patel@northshorelegal.co.nz>
Cc: Rachel Ngata <rachel.ngata@northshorelegal.co.nz>; Mark Allen <mark.allen@harbourfoods.co.nz>
Date: Thursday, 9 May 2026, 5:52 PM
Subject: Instructions for first legal memo

Hi James,

Thanks for moving quickly on this.

For tomorrow's memo, please structure it as follows if possible:

1. Executive summary
2. Recommended transaction approach
3. Key legal issues and red flags
4. Due diligence requests
5. Conditions for indicative offer / SPA
6. Immediate next steps

Please assume the board is not being asked to approve signing yet. The decision is only whether to authorise management to submit a non-binding indicative offer and continue diligence.

My current view is that we should not recommend walking away, but we should be clear that the offer needs to be conditional. The biggest issues appear to be:
- PantryPilot IP ownership and contractor rights;
- GreenFields change of control consent;
- privacy/customer data risks;
- lease consent and renewal;
- employment/founder retention;
- food safety/recall history; and
- bank/internal approvals.

Please also include a short paragraph on confidentiality and communications. We do not want staff, suppliers, or customers hearing about this prematurely.

Regards,

Sarah
` },
  { filename: "14_last_minute_bank_consent.txt", content: `From: David Chen <david.chen@harbourfoods.co.nz>
To: Sarah McKenzie <sarah.mckenzie@harbourfoods.co.nz>
Cc: James Patel <james.patel@northshorelegal.co.nz>; Mark Allen <mark.allen@harbourfoods.co.nz>
Date: Friday, 10 May 2026, 8:14 AM
Subject: Bank consent point

Morning,

I checked the facility agreement.

There is a negative undertaking that Harbour Foods must not acquire any business or shares where the total consideration exceeds NZD $5m without lender consent, unless the acquisition is within an approved annual acquisition basket. The basket has only NZD $2m remaining.

So if we proceed with an $8.2m transaction, we will almost certainly need bank consent before entering a binding agreement. I do not think we need consent for a non-binding indicative offer, provided it is clearly stated to be non-binding and subject to approvals.

Please reflect this in the memo.

Thanks,

David
` },
] as const;
