import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const dir = path.join(__dirname, "../data/acquisition-emails");
const out = path.join(__dirname, "../lib/acquisitionEmailRaw.generated.ts");

const files = fs
  .readdirSync(dir)
  .filter((f) => f.endsWith(".txt") && /^\d{2}_/.test(f))
  .sort();

const entries = files.map((filename) => {
  const content = fs.readFileSync(path.join(dir, filename), "utf8");
  const escaped = content
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\$\{/g, "\\${");
  return `  { filename: ${JSON.stringify(filename)}, content: \`${escaped}\` }`;
});

const ts = `/* eslint-disable */\n/* Auto-generated by scripts/embedAcquisitionEmails.mjs — do not edit */\n\nexport const ACQUISITION_EMAIL_SOURCE_FILES = [\n${entries.join(",\n")},\n] as const;\n`;

fs.writeFileSync(out, ts, "utf8");
console.log(`Wrote ${files.length} emails to ${out}`);
